openapi: 3.0.3
info:
  title: SQL-OPTIMIZER
  version: 1.0.0
servers:
  - url: https://sql-optimizer.azurewebsites.net/
components:
  schemas:
    TestParams:
      type: object
      properties:
        connectionUrl:
          type: string
          required: true
        queries:
          type: array
          required: true
          items:
            type: string
        outputMode:
          type: string
          nullable: true
          enum:
            - HTTP
            - EMAIL
            - SMB
        saveBetter:
          type: boolean
          required: false
          default: false
        outputParams:
          type: string
          required: false
          default: ""
    TestResult:
      type: object
      properties:
        bestIndex:
          type: string
          required: true
        timeBefore:
          type: number
          required: true
        timeAfter:
          type: number
          required: true
        diff:
          type: number
          format: double
          required: true
paths:
  /actions/:
    post:
      summary: Tests SQL-queries for speed with all possible indexes and returns a report.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestParams'
      responses:
        200:
          description: Returns result of autoindexing.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestResult'
            text/csv:
              schema:
                $ref: '#/components/schemas/TestResult'
        400:
          description: Bad request.
          content:
            text/plain:
              schema:
                type: string
        409:
          description: Database is busy.
          content:
            text/plain:
              schema:
                type: string
        5XX:
          description: Unexpected error.
